FROM python:3.11-slim


RUN apt-get update && apt-get install -y --no-install-recommends

RUN pip install --upgrade pip && pip install pipenv

COPY . .

RUN pipenv install 

EXPOSE 8000

CMD ["pipenv", "run", "prod"]